config/routes.rb
Rails.application.routes.draw do

  resources :model
  resources :graph

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'model#index'
  match '/welcome' => 'users#welcome', via: :get
  match '/login' => 'users#login', via: [:get, :post]
  match '/logout' => 'users#logout', via: [:get, :post]
  match '/signup' => 'users#signup', via: [:get, :post]
  match '/profile' => 'users#profile', via: [:get, :post]
  match '/account' => 'users#account', via: [:get, :post]
  #match '/lca' => 'graph#fetch_data', via: :get

end

app/models/user.rb
class User < ApplicationRecord
   has_many :projects
   has_many :assemblys

   # validates_uniqueness_of :username, :on => :create
   # validates_uniqueness_of :email, :on => :create
   validates :email, uniqueness: {message: "Email already taken"}
   validates :username, uniqueness: {message: "Username already taken"}

   validates_presence_of :username
   validates_presence_of :email
   validates_presence_of :password
   validates_presence_of :name

   class_attribute :salt

   def self.salt
      '20ac4d290c2293702c64b3b287ae5ea79b26a5c1'
   end

   def self.authenticate(login, pass)
      User.where(["username = ? OR email = ? AND password = ?", login, login, password_hash(pass)]).first
   end

   def self.authenticate?(login, pass)
      user = self.authenticate(login, pass)
      return false if user.nil?
      return true if user.login == login

      false
   end

   def password=(newpass)
      @password = newpass
   end

   def password(cleartext = nil)
      if cleartext
         @password.to_s
      else
         @password || read_attribute("password")
      end
   end

   protected

   def self.password_hash(pass)
      Digest::SHA1.hexdigest("#{salt}--#{pass}--")
   end

   def password_hash(pass)
      self.class.password_hash(pass)
   end

   before_create :crypt_password

   def crypt_password
      write_attribute "password", password_hash(password(true))
      @password = nil
   end

   before_update :crypt_unless_empty

   def crypt_unless_empty
      if password(true).empty?
         user = self.class.find(self.id)
         write_attribute "password", user.password
      else
         crypt_password
      end
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def welcome
   end

   def profile
      if !session[:user_id]
         redirect_to welcome_path
      else
         @current_user = User.find(session[:user_id])
      end
   end
   
   def account
      if !session[:user_id]
         redirect_to welcome_path
      else
         @current_user = User.find(session[:user_id])
      end
   end

   def logout
      flash[:notice]  = "Successfully Logged Out!"
      session[:user_id] = nil
      cookies.delete :auth_token
      cookies.delete :typo_user_profile
      redirect_to :action => 'welcome'
   end

   def signup
      if request.xhr?
         flash[:ajax] = true
      else
         flash[:ajax] = false
      end
      if request.post?
         if params[:confirm_password] == params[:password]
            new_params = signup_params()
            user = User.new(new_params)
            if user.valid?
               user.save
               puts "VALID USER"
               session[:user_id] = user.id
               redirect_to root_path
            else
               puts user.errors.messages[:email] + user.errors.messages[:username]
               error_mess = "Error: "
               if user.errors.messages[:email] and user.errors.messages[:email].length > 0
                  error_mess += user.errors.messages[:email][0] + ' '
               end
               if user.errors.messages[:username] and user.errors.messages[:username].length > 0
                  error_mess += user.errors.messages[:username][0]
               end
               flash[:error] = error_mess
            end
         else
            flash[:error] = "Your Passwords do not match!"
         end
      end
   end

   def login
      if request.xhr?
         flash[:ajax] = true
      else
         flash[:ajax] = false
      end
      if request.post?
         user = User.authenticate(params[:username], params[:password])
         if user
            session[:user_id] = user.id
            redirect_to root_path
         else
            flash[:error] = 'No Login Found, Try Again!'
         end
      end
   end


   protected

   def signup_params
      params.permit(:username, :password, :name, :email).except(:confirm_password)
   end

   def login_params
      params.permit(:username, :password)
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_navigation.html.erb
<div id="navigation-bar">
   <div id="navigation-container">
      <li style="display: block;"><h1 class="site__title">Focus LCA</h1></li>
      <ul>
         <%= render 'users/navigation_links' %>
      </ul>
   </div>
</div>

app/views/users/_navigation_links.html.erb
<%# add navigation links to this file %>
<div class="user-css">
   <li class='nav-item'> <%= link_to 'Current Project', root_path, method: 'GET', class: 'nav-link' %></li>
   <li class='nav-item'> <%= link_to 'New Project', root_path(:new => true), method: 'GET', class: 'nav-link' %></li>
   <li class='nav-item'> <%= link_to 'All Projects', profile_path, method: 'GET', class: 'nav-link' %></li>
   <li class='nav-item' style="float:right"> <%= link_to 'Logout', logout_path, method: 'GET', class: 'nav-link' %></li>
   <li class='nav-item' style="float:right"> <%= link_to 'Account', account_path, method: 'GET', class: 'nav-link' %></li>
</div>

app/views/users/account.html.erb
<header>
   <%= render 'users/navigation' %>
</header>

<br>

<body>
   <h1>Account</h1><br>
   <p><b>Name: </b><%= @current_user.name %></p><br>
   <p><b>Email: </b><%= @current_user.email %></p><br>
   <p><b>Username: </b><%= @current_user.username %></p><br>
   <p><b>Number of Assemblies: </b><%= @current_user.assemblys.size %></p>
</body>

<br>

app/views/users/login.html.erb
<%- if not flash[:ajax]%>
   <header class="site__header island">
     <div class="wrap">
      <span style="display: block;"><h1 class="site__title mega">Focus LCA</h1></span>
       <span class="beta subhead">The Ultimate LCA Application</span>
     </div>
   </header>
<% end %>

<div id="message_space"> </div>
<%= form_tag login_path, :method => :post do %>

   <!-- <label class="beta subhead"><b>Username</b></label> -->
   <input type="text" class="input" placeholder="Username" name="username" required>

   <!-- <label class="beta subhead"><b>Password</b></label> -->
   <input type="password" class="input" placeholder="Password" name="password" required>

   <button id="signup" class="butt" type="submit">Login</button>

<% end %>

app/views/users/profile.html.erb
<header>
   <%= render 'users/navigation' %>
</header>

<br>
<body>
   <h1>Projects</h1>
   <!--
   <p><b>Name: </b><%= @current_user.name %></p>
   <p><b>Email: </b><%= @current_user.email %></p>
   <p><b>Username: </b><%= @current_user.username %></p>
   <p><b>Number of Assemblies: </b><%= @current_user.assemblys.size %></p>
   -->
</body>

<br>

<% if @current_user.assemblys.size > 0 %>
   <table class="center">
      <tr>
         <th>Assembly</th>
         <th>Last Edited</th>
      </tr>
         <% @current_user.assemblys.order('updated_at DESC').each do |assemb| %>
            <tr>
               <td><%= link_to assemb.name, root_path(:id => assemb.id), method: 'GET', class: 'nav-link' %></td>
               <td><%= assemb.updated_at %></td>
            </tr>
         <% end %>

   </table>
<% end %>

app/views/users/signup.html.erb
<%- if not flash[:ajax]%>
   <header class="site__header island">
     <div class="wrap">
      <span style="display: block;"><h1 class="site__title mega">Focus LCA</h1></span>
       <span class="beta subhead">The Ultimate LCA Application</span>
     </div>
   </header>
<% end %>

<div id="message_space"> </div>
<%= form_tag signup_path, :method => :post do %>

   <!-- <label class="beta subhead"><b>Full Name</b></label> -->
   <input type="text" class="input" placeholder="Full Name" name="name" required>
   <br>
   <br>

   <input type="text" class="input" placeholder="Username" name="username" required>
   <br>
   <br>

   <input type="text" class="input" placeholder="Email" name="email" required>
   <br>
   <br>
   <!-- <label class="beta subhead"><b>Password</b></label> -->

   <input type="password" class="input" placeholder="Password" name="password" required>
   <br>
   <br>

   <input type="password" class="input" placeholder="Confirm Password" name="confirm_password" required>
   <br>
   <br>
   <button id="signup" class="butt" type="submit">Signup</button>

<% end %>

app/views/users/welcome.html.erb
<!DOCTYPE html>

<body>
<header class="site__header island">
  <div class="wrap">
   <span style="display: block;"><h1 class="site__title mega">Focus LCA</h1></span>
   <span class="beta subhead">The Ultimate LCA Application</span>
  </div>
</header>

<main id= "animator" class="site__content island " role="content">

   <button id="login_button" class="butt js--triggerAnimation">Login</button>
   <button id="signup_button" class="butt js--triggerAnimation">Signup</button>

   <div id="loadcontent" >
   </div>

</main><!-- /.site__content -->


</body>